processingtime_1e2_5_sBH_SG=loadtxt("capturedata/processingtime/processingtime_1e2_5_sBH_SG.txt")
processingtime_1e3_5_sBH_SG=loadtxt("capturedata/processingtime/processingtime_1e3_5_sBH_SG.txt")
processingtime_2e3_5_sBH_SG=loadtxt("capturedata/processingtime/processingtime_2e3_5_sBH_SG.txt")
processingtime_5e3_5_sBH_SG=loadtxt("capturedata/processingtime/processingtime_5e3_5_sBH_SG.txt")
processingtime_1e4_5_sBH_SG=loadtxt("capturedata/processingtime/processingtime_1e4_5_sBH_SG.txt")
processingtime_1e5_5_sBH_SG=loadtxt("capturedata/processingtime/processingtime_1e5_5_sBH_SG.txt")
processingtime_5e5_5_sBH_SG=loadtxt("capturedata/processingtime/processingtime_5e5_5_sBH_SG.txt")

processingtime_1e4_15_sBH_SG=loadtxt("capturedata/processingtime/processingtime_1e4_15_sBH_SG.txt")
processingtime_1e5_15_sBH_SG=loadtxt("capturedata/processingtime/processingtime_1e5_15_sBH_SG.txt")
processingtime_5e5_15_sBH_SG=loadtxt("capturedata/processingtime/processingtime_5e5_15_sBH_SG.txt")
processingtime_1e6_15_sBH_SG=loadtxt("capturedata/processingtime/processingtime_1e6_15_sBH_SG.txt")

processingtime_5e5_30_sBH_SG=loadtxt("capturedata/processingtime/processingtime_5e5_30_sBH_SG.txt")
processingtime_1e6_30_sBH_SG=loadtxt("capturedata/processingtime/processingtime_1e6_30_sBH_SG.txt")

processingtime_5e5_45_sBH_SG=loadtxt("capturedata/processingtime/processingtime_5e5_45_sBH_SG.txt")
processingtime_1e6_45_sBH_SG=loadtxt("capturedata/processingtime/processingtime_1e6_45_sBH_SG.txt")

processingtime_1e6_60_sBH_SG=loadtxt("capturedata/processingtime/processingtime_1e6_60_sBH_SG.txt")

processingtime_1e6_80_sBH_SG=loadtxt("capturedata/processingtime/processingtime_1e6_80_sBH_SG.txt")
processingtime_1e7_80_sBH_SG=loadtxt("capturedata/processingtime/processingtime_1e7_80_sBH_SG.txt")


processingtime_1e3_5_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_1e3_5_sBH_TQM.txt")
processingtime_2e3_5_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_2e3_5_sBH_TQM.txt")
processingtime_1e4_5_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_1e4_5_sBH_TQM.txt")
processingtime_2e4_5_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_2e4_5_sBH_TQM.txt")
processingtime_3e4_5_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_3e4_5_sBH_TQM.txt")
processingtime_4e4_5_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_4e4_5_sBH_TQM.txt")
processingtime_5e4_5_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_5e4_5_sBH_TQM.txt")
processingtime_1e5_5_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_1e5_5_sBH_TQM.txt")
processingtime_2e5_5_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_2e5_5_sBH_TQM.txt")
processingtime_5e5_5_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_5e5_5_sBH_TQM.txt")
processingtime_1e6_5_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_1e6_5_sBH_TQM.txt")
processingtime_5e6_5_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_5e6_5_sBH_TQM.txt")
processingtime_8e6_5_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_8e6_5_sBH_TQM.txt")

processingtime_1e5_15_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_1e5_15_sBH_TQM.txt")
processingtime_1e6_15_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_1e6_15_sBH_TQM.txt")
processingtime_5e6_15_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_5e6_15_sBH_TQM.txt")
processingtime_1e7_15_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_1e7_15_sBH_TQM.txt")

processingtime_1e6_30_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_1e6_30_sBH_TQM.txt")
processingtime_5e6_30_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_5e6_30_sBH_TQM.txt")
processingtime_1e7_30_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_1e7_30_sBH_TQM.txt")

processingtime_5e6_45_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_5e6_45_sBH_TQM.txt")
processingtime_1e7_45_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_1e7_45_sBH_TQM.txt")

processingtime_5e6_60_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_5e6_60_sBH_TQM.txt")
processingtime_1e7_60_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_1e7_60_sBH_TQM.txt")

processingtime_1e7_80_sBH_TQM=loadtxt("capturedata/processingtime/processingtime_1e7_80_sBH_TQM.txt")

processingtime_1e1_45_rgiant_SG=loadtxt("capturedata/processingtime/processingtime_1e1_45_rgiant_SG.txt")
processingtime_1e2_45_rgiant_SG=loadtxt("capturedata/processingtime/processingtime_1e2_45_rgiant_SG.txt")
processingtime_1e3_45_rgiant_SG=loadtxt("capturedata/processingtime/processingtime_1e3_45_rgiant_SG.txt")
processingtime_1e4_45_rgiant_SG=loadtxt("capturedata/processingtime/processingtime_1e4_45_rgiant_SG.txt")
processingtime_1e5_45_rgiant_SG=loadtxt("capturedata/processingtime/processingtime_1e5_45_rgiant_SG.txt")
processingtime_1e6_45_rgiant_SG=loadtxt("capturedata/processingtime/processingtime_1e6_45_rgiant_SG.txt")
processingtime_1e7_45_rgiant_SG=loadtxt("capturedata/processingtime/processingtime_1e7_45_rgiant_SG.txt")

processingtime_1e4_5_rgiant_SG=loadtxt("capturedata/processingtime/processingtime_1e4_5_rgiant_SG.txt")
processingtime_1e4_15_rgiant_SG=loadtxt("capturedata/processingtime/processingtime_1e4_15_rgiant_SG.txt")
processingtime_1e4_30_rgiant_SG=loadtxt("capturedata/processingtime/processingtime_1e4_30_rgiant_SG.txt")
processingtime_1e4_60_rgiant_SG=loadtxt("capturedata/processingtime/processingtime_1e4_60_rgiant_SG.txt")
processingtime_1e4_80_rgiant_SG=loadtxt("capturedata/processingtime/processingtime_1e4_80_rgiant_SG.txt")

processingtime_1e2_45_ostar_SG=loadtxt("capturedata/processingtime/processingtime_1e2_45_ostar_SG.txt")
processingtime_1e3_45_ostar_SG=loadtxt("capturedata/processingtime/processingtime_1e3_45_ostar_SG.txt")
processingtime_1e4_45_ostar_SG=loadtxt("capturedata/processingtime/processingtime_1e4_45_ostar_SG.txt")
processingtime_1e5_45_ostar_SG=loadtxt("capturedata/processingtime/processingtime_1e5_45_ostar_SG.txt")

processingtime_1e4_5_ostar_SG=loadtxt("capturedata/processingtime/processingtime_1e4_5_ostar_SG.txt")
processingtime_1e4_15_ostar_SG=loadtxt("capturedata/processingtime/processingtime_1e4_15_ostar_SG.txt")
processingtime_1e4_30_ostar_SG=loadtxt("capturedata/processingtime/processingtime_1e4_30_ostar_SG.txt")
processingtime_1e4_60_ostar_SG=loadtxt("capturedata/processingtime/processingtime_1e4_60_ostar_SG.txt")
processingtime_1e4_80_ostar_SG=loadtxt("capturedata/processingtime/processingtime_1e4_80_ostar_SG.txt")

processingtime_1e2_45_gstar_SG=loadtxt("capturedata/processingtime/processingtime_1e2_45_gstar_SG.txt")
processingtime_1e3_45_gstar_SG=loadtxt("capturedata/processingtime/processingtime_1e3_45_gstar_SG.txt")
processingtime_1e4_45_gstar_SG=loadtxt("capturedata/processingtime/processingtime_1e4_45_gstar_SG.txt")

processingtime_1e4_5_gstar_SG=loadtxt("capturedata/processingtime/processingtime_1e4_5_gstar_SG.txt")
processingtime_1e4_15_gstar_SG=loadtxt("capturedata/processingtime/processingtime_1e4_15_gstar_SG.txt")
processingtime_1e4_30_gstar_SG=loadtxt("capturedata/processingtime/processingtime_1e4_30_gstar_SG.txt")
processingtime_1e4_60_gstar_SG=loadtxt("capturedata/processingtime/processingtime_1e4_60_gstar_SG.txt")
processingtime_1e4_80_gstar_SG=loadtxt("capturedata/processingtime/processingtime_1e4_80_gstar_SG.txt")

processingtime_1e2_45_mstar_SG=loadtxt("capturedata/processingtime/processingtime_1e2_45_mstar_SG.txt")
processingtime_1e3_45_mstar_SG=loadtxt("capturedata/processingtime/processingtime_1e3_45_mstar_SG.txt")
processingtime_1e4_45_mstar_SG=loadtxt("capturedata/processingtime/processingtime_1e4_45_mstar_SG.txt")

processingtime_1e4_5_mstar_SG=loadtxt("capturedata/processingtime/processingtime_1e4_5_mstar_SG.txt")
processingtime_1e4_15_mstar_SG=loadtxt("capturedata/processingtime/processingtime_1e4_15_mstar_SG.txt")
processingtime_1e4_30_mstar_SG=loadtxt("capturedata/processingtime/processingtime_1e4_30_mstar_SG.txt")
processingtime_1e4_60_mstar_SG=loadtxt("capturedata/processingtime/processingtime_1e4_60_mstar_SG.txt")
processingtime_1e4_80_mstar_SG=loadtxt("capturedata/processingtime/processingtime_1e4_80_mstar_SG.txt")

processingtime_1e2_45_rgiant_TQM=loadtxt("capturedata/processingtime/processingtime_1e2_45_rgiant_TQM.txt")
processingtime_1e3_45_rgiant_TQM=loadtxt("capturedata/processingtime/processingtime_1e3_45_rgiant_TQM.txt")
processingtime_1e4_45_rgiant_TQM=loadtxt("capturedata/processingtime/processingtime_1e4_45_rgiant_TQM.txt")
processingtime_1e5_45_rgiant_TQM=loadtxt("capturedata/processingtime/processingtime_1e5_45_rgiant_TQM.txt")
processingtime_1e6_45_rgiant_TQM=loadtxt("capturedata/processingtime/processingtime_1e6_45_rgiant_TQM.txt")
processingtime_1e7_45_rgiant_TQM=loadtxt("capturedata/processingtime/processingtime_1e7_45_rgiant_TQM.txt")

processingtime_1e4_5_rgiant_TQM=loadtxt("capturedata/processingtime/processingtime_1e4_5_rgiant_TQM.txt")
processingtime_1e4_15_rgiant_TQM=loadtxt("capturedata/processingtime/processingtime_1e4_15_rgiant_TQM.txt")
processingtime_1e4_30_rgiant_TQM=loadtxt("capturedata/processingtime/processingtime_1e4_30_rgiant_TQM.txt")
processingtime_1e4_60_rgiant_TQM=loadtxt("capturedata/processingtime/processingtime_1e4_60_rgiant_TQM.txt")
processingtime_1e4_80_rgiant_TQM=loadtxt("capturedata/processingtime/processingtime_1e4_80_rgiant_TQM.txt")

processingtime_1e4_30_ostar_TQM=loadtxt("capturedata/processingtime/processingtime_1e4_30_ostar_TQM.txt")